spring:
  datasource:
    url: 'jdbc:mysql://123.57.27.150:3306/mentorselection?createDatabaseIfNotExist=true&serverTimezone=Asia/Shanghai'
    username: 2046
    password: 6402
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10
      max-lifetime: 30000
      connection-test-query: select 1
  jackson:
    default-property-inclusion: non_null # 序列化时忽略空值属性
  sql:
    init:
      mode: always

logging:
  level:
    root: info
    com:
      example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'

my:
  salt: 636eac2534bcfcc0

---
spring:
  datasource:
    url: 'jdbc:mysql://${dhost}/mentorselection?createDatabaseIfNotExist=true&serverTimezone=Asia/Shanghai'
    username: ${dusername}
    password: ${dpassword}
  config:
    activate:
      on-profile: prod
my:
  salt: ${salt}
logging:
  level:
    root: info
    com:
      example: info
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'
