spring:
  sql:
    init:
      mode: always
  r2dbc:
    url: r2dbcs:mysql://123.57.27.150:3306/mentorselection?createDatabaseIfNotExist=true&serverTimezone=Asia/Shanghai
    username: 2046
    password: 6402
    pool:
      enabled: true
      initial-size: 1
      validation-query: select 1
      max-life-time: 30000

  jackson:
    default-property-inclusion: non_null # 序列化时忽略空值属性

logging:
  level:
    root: info
    com:
      example: debug
    org:
      springframework:
        r2dbc: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'

my:
  secretkey: 636eac2534bcfcc0

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: r2dbcs:mysql://${dhost}/mentorselection?createDatabaseIfNotExist=true&serverTimezone=Asia/Shanghai
    username: ${dusername}
    password: ${dpassword}
  r2dbc:
    pool:
      max-size: 200
my:
  secretkey: ${secretkey}
logging:
  level:
    root: info
    com:
      example: info
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'
